import 'package:finance_control_ui/finance_control_ui.dart';
import 'package:flutter/material.dart';

class FinanceSelectBank extends StatefulWidget {
  const FinanceSelectBank({super.key});

  @override
  State<FinanceSelectBank> createState() => _FinanceSelectBankState();
}

class _FinanceSelectBankState extends State<FinanceSelectBank> {
  String? selectedItem;

  List<String> banks = [
    "American Express",
    "Mastercard",
    "Visa",
    "Credicard",
    "Diners",
    "Elo",
    "Nubank",
    "Aura",
    "Banco Inter",
    "Banco do Brasil",
    "Bradesco",
    "Caixa",
    "Hipercard",
    "Itaú",
    "Neon",
    "Next",
    "Nuconta",
    "Santander",
    "Agibank",
    "Amazonia",
    "Ame Digital",
    "BMG",
    "BRB",
    "BRDE",
    "BS2",
    "BTG Pactual",
    "Banco Cacique",
    "Banco PAN",
    "Banco Votorantim",
    "Banco do Nordeste",
    "Banese",
    "Banestes",
    "Banif",
    "Banpara",
    "Banrisul",
    "Bbm",
    "Cetelem",
    "Citibank",
    "Clear",
    "Cruzeirodosul",
    "Daycoval",
    "Digi+",
    "Digio",
    "Diin",
    "Nuinvest",
    "Elliot",
    "Fortbrasil",
    "Genial Investimentos",
    "HSBC",
    "IQ Option",
    "Iti",
    "Magnetis",
    "Mais!",
    "Mercadopago",
    "ModalMais",
    "Moip",
    "Monetus",
    "N26",
    "Nova Futura",
    "Original",
    "Pag!",
    "PagBank",
    "Pagseguro",
    "PayU Brasil",
    "Paypal",
    "PicPay",
    "Recargapay",
    "Rico",
    "Safra",
    "Sicoob",
    "Sicredi",
    "Sodexo",
    "Sofisa direto",
    "Submarino",
    "Toro Investimentos",
    "Unicred",
    "Uniprime",
    "Urbe.Me",
    "Viacredi",
    "ABN AMRO",
    "AGBank",
    "AKBank",
    "AMP Personal Banking",
    "ANZ",
    "ASN",
    "Absolut Bank",
    "Agribank",
    "Aktia",
    "Alfa",
    "Alpha",
    "Americanas",
    "Ameriprise Financial",
    "Attica",
    "BBVA",
    "BCA",
    "BIDV",
    "BMO",
    "BNI",
    "BNL",
    "BNP Paribas",
    "BOQ",
    "BPER Banca",
    "BPI",
    "BRI",
    "Banamex",
    "Banca Carige",
    "Banca DItalia",
    "Banca MPS",
    "Banca Mediolanum",
    "Banca Populare di Sondrio",
    "Banco BPM",
    "Banco de Bogotá",
    "Banco de Occident",
    "Banco del Bajio",
    "BancoPosta",
    "Bancolombia",
    "Bangkok Bank",
    "Bank Norwegian",
    "Bank Rakyat",
    "Bank of Aland",
    "Bank of America",
    "Bank of China",
    "Bankia",
    "Bankwest",
    "Banorte",
    "Barclays",
    "Ben Visa Vale",
    "Bendigo",
    "C6 Bank",
    "CDB",
    "CDP",
    "CIBC",
    "CIMB Bank",
    "CIMB Niaga",
    "CTT",
    "Caisse dEpargne",
    "Caixa Geral",
    "CaixaBank",
    "Capital One",
    "Carteira",
    "Cassa Depositi e Prestiti",
    "Charles Schwab",
    "China Construction",
    "CommBank",
    "Commerzbank",
    "Credit Bank of Moscow",
    "Credit agricole",
    "Credito Emiliano",
    "Crédit Agricole",
    "Crédit du Nord",
    "DNB",
    "DZ Bank",
    "Danske",
    "Davivienda",
    "Default",
    "Deutsche Bank",
    "Eurobank",
    "Evli",
    "Forex",
    "Galicia",
    "Garanti",
    "Gazprombank",
    "Goldman Sachs",
    "Handelsbanken",
    "Hipotecario",
    "Hong Leong",
    "HypoVereinsbank",
    "ICBC",
    "ICCREA Banca",
    "ING",
    "Inbursa",
    "Intesa Sanpaolo",
    "Isbank",
    "JP",
    "JP Morgan Chase",
    "Jyske",
    "KB Kookmin",
    "KBank",
    "KDB",
    "KEB Hana",
    "KFW",
    "Krung Thai Bank",
    "Lloyds Banking Group",
    "MUFG",
    "Macquarie",
    "Macro",
    "Mandiri",
    "Maybank",
    "MedioBanca",
    "Millenium BCP",
    "Mizuho",
    "Morgan Stanley",
    "NAB",
    "NH",
    "Nación",
    "National Bank of Greece",
    "Nochu",
    "Nordea",
    "Nordnet",
    "Novo Banco",
    "Nykredit",
    "OP",
    "Otkritie",
    "Outros",
    "PNC Financial Services",
    "Patagonia",
    "Piraeus",
    "Porto Seguro",
    "Promsvyazbank",
    "Public Bank",
    "RBC Royal",
    "RBS",
    "RHB",
    "Rabobank",
    "Raiffeisen Bank",
    "Revolut",
    "SCB",
    "SEB",
    "SMBC",
    "SMP Bank",
    "SNS",
    "Sabadell",
    "Santander Espanha",
    "Santander México",
    "Sberbank",
    "Scotiabank",
    "Senff",
    "Shinhan",
    "Société Générale",
    "Sparebank 1 SMN",
    "Standard Chartered",
    "Storebrand",
    "Suncorp",
    "Superdigital",
    "Swedbank",
    "SydBank",
    "TD Bank",
    "TMB Bank",
    "Techcombank",
    "Tesouro Direto",
    "Tesouro Nacional",
    "Ticket",
    "Tinkoff",
    "TransferWise",
    "Trigg",
    "UBI Banca",
    "US Bank",
    "Unicredit Bank",
    "Unipol Banca",
    "UrPay",
    "VTB",
    "Vietcombank",
    "VietinBank",
    "Warren",
    "Wells Fargo",
    "Westpac",
    "Woop",
    "Xdex",
    "Xp Investimentos",
    "Yapi Kredi Bank",
    "Ziraat",
    "alelo",
    "bunq",
    "Órama",
    "Flash",
    "Cora",
    "Will",
    "UTIL",
    "Caju",
  ];

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<List<String>>(
      // Substitua este valueListenable pelo seu valor real.
      valueListenable: ValueNotifier<List<String>>(banks),
      builder: (context, categories, child) {
        return SizedBox(
          height: 56,
          width: double.infinity,
          child: Material(
            elevation: 1,
            borderRadius: BorderRadius.circular(8),
            child: InkWell(
              onTap: () {
                showModalBottomSheet(
                  context: context,
                  shape: const RoundedRectangleBorder(
                    borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(30),
                      topRight: Radius.circular(30),
                    ),
                  ),
                  elevation: 3,
                  backgroundColor: AppColors.white,
                  builder: (context) {
                    return StatefulBuilder(
                      builder: (BuildContext context, StateSetter setState) {
                        final searchController = TextEditingController();

                        List<String> filteredBanks = [...banks];

                        // Função para filtrar os bancos com base na pesquisa.
                        void filterBanks(String query) {
                          setState(() {
                            filteredBanks = banks
                                .where((bank) => bank
                                    .toLowerCase()
                                    .contains(query.toLowerCase()))
                                .toList();
                          });
                        }

                        return Container(
                          height: 500,
                          padding: const EdgeInsets.all(16),
                          width: double.infinity,
                          child: Column(
                            children: [
                              Container(
                                height: 4,
                                width: 30,
                                decoration: BoxDecoration(
                                  color: AppColors.slateGray,
                                  borderRadius: BorderRadius.circular(2),
                                ),
                              ),
                              const SizedBox(height: 20),
                              TextField(
                                controller: searchController,
                                onChanged: filterBanks,
                                decoration: const InputDecoration(
                                  hintText: 'Pesquisar bancos',
                                  prefixIcon: Icon(Icons.search),
                                ),
                              ),
                              const SizedBox(height: 16),
                              Expanded(
                                child: ListView.builder(
                                  itemCount: filteredBanks.length,
                                  itemBuilder: (context, index) {
                                    return FinanceText.p16(
                                      filteredBanks[index],
                                    );
                                  },
                                ),
                              ),
                            ],
                          ),
                        );
                      },
                    );
                  },
                );
              },
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        );
      },
    );
  }
}
